#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 David D. Karnowski
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
compare_sessions.py — the expected pull against the observed one.

    python tools/compare_sessions.py EXPECTED OBSERVED [--amps 40] [--json]

Each side is a replay fixture (`.json`, `record_session.py` format), a
readings database (`.db`, the reader's or the pull's), or a captured frame
stream (`.jsonl`, the MQTT `rx/#` message format of docs/MQTT.md — what
`mosquitto_sub` or `hakake_sim.py --pull` writes). The tool prints, side by
side and with the difference:

  * peak pack current, its time, speed and power
  * time to peak from the start of the pull (current first below −amps)
  * the lowest cell-pair voltage and which pair
  * pack voltage sag (rest before the pull → lowest under it)
  * SOC drop over the pull and over the whole input
  * per-id frame periods observed in a stream, against the survey

The EXPECTED side today is `tests/fixtures/session_leaf_ze0_pull_sim.json`,
generated by the simulator: its Car-CAN lines are the encoder's and every
EV-CAN byte in it is ASSERTED from public documentation. When the CANable
arrives, the owner records the same manoeuvre, feeds it in as OBSERVED, and
the differences say where the model and the assumed bytes are wrong. That
is the purpose of this tool; a match proves consistency, not truth.

Read-only: this tool never touches a car or an adapter. It opens the
database read-only and never writes a row.
"""

import argparse
import json
import os
import statistics
import sys
import tempfile

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
for _p in (_ROOT, os.path.join(_ROOT, "web")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

DEFAULT_AMPS = 40.0
EV_IDS = ("1DB", "1DA", "1D4", "55B", "5BC", "11A", "1DC")


# ── loading ──────────────────────────────────────────────────────────────

def _item_maps(profile):
    """(tx, cmd) -> item, passive id -> item, from the profile's ITEMS/TARGETS."""
    by_uds, by_id = {}, {}
    targets = getattr(profile, "TARGETS", {}) or {}
    for name, it in (getattr(profile, "ITEMS", {}) or {}).items():
        pair = targets.get(it.get("kind"))
        if pair and it.get("cmd"):
            by_uds[(pair[0].upper(), it["cmd"].upper())] = name
        elif it.get("id"):
            by_id[it["id"].upper()] = name
    return by_uds, by_id


def _sample_from_record(t, rec):
    cells = rec.get("cells") or []
    s = {"t": t, "current_a": rec.get("current_a"), "pack_v": rec.get("pack_v"),
         "soc": rec.get("soc"), "speed_mph": rec.get("speed_mph"),
         "cell_min": rec.get("cell_min"), "cell_min_no": rec.get("cell_min_no")}
    if cells:
        s["cell_min"] = min(cells)
        s["cell_min_no"] = cells.index(min(cells)) + 1
    return s


def load_fixture(path, vehicle=None):
    """A replay fixture → series. UDS answers go through the profile's own
    `decode()`; 0x1DB lines through the simulator's ASSERTED decoder."""
    from vehicles import get_vehicle
    from simulator.canbus import decode_1db

    with open(path) as f:
        doc = json.load(f)
    if "frames" not in doc:
        raise ValueError(f"{path}: not a replay fixture")
    profile = get_vehicle(vehicle or doc.get("vehicle"))
    by_uds, by_id = _item_maps(profile)
    samples, counts = [], {}
    n_frames = len(doc["frames"])
    width = None
    if n_frames > 1:
        ts = [float(fr.get("t", 0.0)) for fr in doc["frames"]]
        width = statistics.median(b - a for a, b in zip(ts, ts[1:])) or None
    for fr in doc["frames"]:
        t = float(fr.get("t", 0.0))
        responses = {}
        for tx, cmds in (fr.get("uds") or {}).items():
            for cmd, lines in cmds.items():
                item = by_uds.get((tx.upper(), cmd.upper()))
                if item:
                    responses[item] = lines
        for cid, lines in (fr.get("passive") or {}).items():
            counts[cid.upper()] = counts.get(cid.upper(), 0) + len(lines)
            item = by_id.get(cid.upper())
            if item:
                responses[item] = lines
        rec, _ = profile.decode(responses) if responses else ({}, None)
        s = _sample_from_record(t, rec)
        ev = (fr.get("passive") or {}).get("1DB")
        if ev:
            d = decode_1db(bytes(int(b, 16) for b in ev[-1].split()[1:]))
            s["ev_current_a"], s["ev_pack_v"] = d["current_a"], d["pack_v"]
        samples.append(s)
    return {"source": path, "kind": "fixture", "synthetic": bool(doc.get("synthetic")),
            "vehicle": profile.NAME, "samples": samples, "periods": {}, "counts": counts,
            "frame_width_s": width, "note": doc.get("notes", "")}


def load_db(path, vehicle=None):
    """A readings database → series, through `Store.frames()` (the same rows
    Playback draws). Opened read-only."""
    import sqlite3
    from store import Store

    ro = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    try:
        names = [r[0] for r in ro.execute("SELECT DISTINCT vehicle FROM readings")]
        meta = dict(ro.execute("SELECT key, value FROM meta").fetchall())
    finally:
        ro.close()
    vehicle = vehicle or (names[0] if names else None)
    st = Store(path, vehicle=vehicle)
    try:
        t0, t1 = st.conn.execute("SELECT MIN(ts_epoch), MAX(ts_epoch) FROM readings").fetchone()
        if t0 is None:
            raise ValueError(f"{path}: no readings")
        fr = st.frames(t0, t1, max_points=100000, cells=True)
    finally:
        st.close()
    samples = [_sample_from_record(t, rec) for t, rec in zip(fr["t"], fr["records"])]
    return {"source": path, "kind": "db", "synthetic": meta.get("synthetic") == "true",
            "vehicle": vehicle, "samples": samples, "periods": {}, "counts": {},
            "frame_width_s": None, "note": meta.get("warning", "")}


def stream_periods(path):
    """Median inter-frame gap per id in a JSON-lines stream, and counts."""
    from record_session import mqtt_stream_events

    last, gaps, counts = {}, {}, {}
    for ev in mqtt_stream_events(path):
        if ev[0] != "frame":
            continue
        _, t, cid, _line = ev
        cid = cid.upper()
        counts[cid] = counts.get(cid, 0) + 1
        if cid in last:
            gaps.setdefault(cid, []).append(t - last[cid])
        last[cid] = t
    periods = {cid: round(statistics.median(g), 4) for cid, g in gaps.items() if g}
    return periods, counts


def load_stream(path, vehicle=None, period=0.5):
    """A captured `rx/#` stream → series: exact per-id periods from the
    stream itself, the samples through a temporary fixture built by
    `record_session.from_mqtt()` (so a stream and a fixture decode alike)."""
    from record_session import from_mqtt
    from simulator.pull import thin_stream_strided, _topic_bus_id

    periods, counts = stream_periods(path)
    # A two-channel stream (the rig's, or a bridge on each bus) carries some
    # ids on both — 0x284 is a VCM relay on EV-CAN with another payload — so
    # only the car bus feeds the profile's decoders; from EV-CAN only the
    # ASSERTED ids are kept, and a single-bus capture is taken whole.
    buses = set()
    with open(path) as f:
        for raw in f:
            try:
                msg = json.loads(raw)
            except json.JSONDecodeError:
                continue
            if "/rx/" in msg.get("topic", ""):
                buses.add(_topic_bus_id(msg["topic"], msg.get("payload"))[0])
    tmpdir = tempfile.mkdtemp(prefix="hakake-compare-")
    tmp, thinned = os.path.join(tmpdir, "fixture.json"), os.path.join(tmpdir, "stream.jsonl")
    try:
        src = path
        if len(buses) > 1:
            strides = {("car", cid): 1 for cid in counts}
            strides.update({("ev", cid): 1 for cid in EV_IDS})
            thin_stream_strided(path, thinned, strides)
            src = thinned
        from_mqtt(src, out=tmp, vehicle=vehicle, period=period, log=lambda *a: None)
        series = load_fixture(tmp, vehicle=vehicle)
    finally:
        for fpath in (tmp, thinned):
            try:
                os.remove(fpath)
            except OSError:
                pass
        try:
            os.rmdir(tmpdir)
        except OSError:
            pass
    series.update({"source": path, "kind": "stream", "periods": periods, "counts": counts})
    return series


def load_series(path, vehicle=None):
    ext = os.path.splitext(path)[1].lower()
    if ext == ".db":
        return load_db(path, vehicle)
    if ext == ".jsonl":
        return load_stream(path, vehicle)
    return load_fixture(path, vehicle)


# ── the numbers ──────────────────────────────────────────────────────────

def _first(samples, key):
    for s in samples:
        if s.get(key) is not None:
            return s
    return None


def _last(samples, key):
    for s in reversed(samples):
        if s.get(key) is not None:
            return s
    return None


def metrics(series, amps=DEFAULT_AMPS):
    """The pull's numbers from one series. Times are seconds from the series'
    first sample, so a fixture (offsets) and a database (epoch) compare."""
    samples = [s for s in series["samples"] if s.get("current_a") is not None]
    if not samples:
        return {"error": "no current samples"}
    t0 = series["samples"][0]["t"]
    rel = lambda t: round(t - t0, 2)                                      # noqa: E731
    peak = min(samples, key=lambda s: s["current_a"])
    start = next((s for s in samples if s["current_a"] < -amps), None)
    end = None
    if start:
        after = [s for s in samples if s["t"] >= peak["t"] and s["current_a"] >= -amps]
        end = after[0] if after else samples[-1]
    before = [s for s in samples if s["t"] < start["t"]] if start else []
    rest = before[-1] if before else samples[0]
    with_v = [s for s in samples if s.get("pack_v") is not None]
    low_v = min(with_v, key=lambda s: s["pack_v"]) if with_v else None
    with_c = [s for s in series["samples"] if s.get("cell_min") is not None]
    low_c = min(with_c, key=lambda s: s["cell_min"]) if with_c else None
    soc_first, soc_last = _first(series["samples"], "soc"), _last(series["samples"], "soc")
    out = {
        "samples": len(series["samples"]),
        "span_s": rel(series["samples"][-1]["t"]),
        "peak_a": peak["current_a"], "t_peak_s": rel(peak["t"]),
        "peak_speed_mph": peak.get("speed_mph"),
        "peak_kw": (round(peak["current_a"] * peak["pack_v"] / 1000.0, 2)
                    if peak.get("pack_v") is not None else None),
        "pull_start_s": rel(start["t"]) if start else None,
        "time_to_peak_s": round(peak["t"] - start["t"], 2) if start else None,
        "pull_duration_s": round(end["t"] - start["t"], 2) if start and end else None,
        "rest_v": rest.get("pack_v"),
        "min_v": low_v["pack_v"] if low_v else None,
        "sag_v": (round(rest["pack_v"] - low_v["pack_v"], 2)
                  if low_v and rest.get("pack_v") is not None else None),
        "min_cell_mv": low_c["cell_min"] if low_c else None,
        "min_cell_pair": low_c.get("cell_min_no") if low_c else None,
        "t_min_cell_s": rel(low_c["t"]) if low_c else None,
        "soc_first": soc_first["soc"] if soc_first else None,
        "soc_last": soc_last["soc"] if soc_last else None,
        "soc_drop": (round(soc_first["soc"] - soc_last["soc"], 3)
                     if soc_first and soc_last else None),
    }
    if start and end:
        s0 = _first([s for s in series["samples"] if s["t"] >= start["t"]], "soc")
        s1 = _last([s for s in series["samples"] if s["t"] <= end["t"]], "soc")
        out["soc_drop_pull"] = round(s0["soc"] - s1["soc"], 3) if s0 and s1 else None
    else:
        out["soc_drop_pull"] = None
    ev = [s for s in series["samples"] if s.get("ev_current_a") is not None]
    if ev:
        p = min(ev, key=lambda s: s["ev_current_a"])
        out["ev_peak_a"], out["ev_t_peak_s"] = p["ev_current_a"], rel(p["t"])
    return out


METRIC_ROWS = [
    ("peak current (A)", "peak_a"), ("  at t (s)", "t_peak_s"), ("  speed (mph)", "peak_speed_mph"),
    ("  power (kW)", "peak_kw"), ("pull start (s, < -amps)", "pull_start_s"),
    ("time to peak (s)", "time_to_peak_s"), ("pull duration (s)", "pull_duration_s"),
    ("pack V at rest", "rest_v"), ("pack V lowest", "min_v"), ("pack sag (V)", "sag_v"),
    ("lowest cell (mV)", "min_cell_mv"), ("  pair no.", "min_cell_pair"), ("  at t (s)", "t_min_cell_s"),
    ("SOC first (%)", "soc_first"), ("SOC last (%)", "soc_last"), ("SOC drop, pull (%)", "soc_drop_pull"),
    ("SOC drop, whole (%)", "soc_drop"), ("0x1DB peak (A, ASSERTED bytes)", "ev_peak_a"),
    ("  at t (s)", "ev_t_peak_s"), ("samples", "samples"), ("span (s)", "span_s"),
]


def compare(expected, observed, amps=DEFAULT_AMPS):
    me, mo = metrics(expected, amps), metrics(observed, amps)
    rows = []
    for label, key in METRIC_ROWS:
        a, b = me.get(key), mo.get(key)
        if a is None and b is None:
            continue
        delta = None
        if isinstance(a, (int, float)) and isinstance(b, (int, float)) and key != "min_cell_pair":
            delta = round(b - a, 3)
        rows.append({"metric": label, "expected": a, "observed": b, "delta": delta})
    periods = period_rows(expected, observed)
    return {"amps": amps, "expected": me, "observed": mo, "rows": rows, "periods": periods}


def period_rows(expected, observed):
    """Per-id periods: the survey, the expected stream's, the observed
    stream's. A fixture has no per-frame timestamps (only counts per
    timeline frame), so only a `.jsonl` input fills its column."""
    try:
        from simulator.canbus import PERIODS
        survey = {}
        for bus in ("car", "ev"):
            for cid, ms in PERIODS[bus].get("leaf_ze0", {}).items():
                survey.setdefault(cid, ms / 1000.0)
    except Exception:
        survey = {}
    ids = sorted(set(expected.get("periods", {})) | set(observed.get("periods", {}))
                 | set(expected.get("counts", {})) | set(observed.get("counts", {})))
    out = []
    for cid in ids:
        out.append({"id": cid, "survey_s": survey.get(cid),
                    "expected_s": expected.get("periods", {}).get(cid),
                    "observed_s": observed.get("periods", {}).get(cid),
                    "expected_n": expected.get("counts", {}).get(cid),
                    "observed_n": observed.get("counts", {}).get(cid)})
    return out


# ── printing ─────────────────────────────────────────────────────────────

def _fmt(v):
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:.3g}" if abs(v) < 1 else f"{v:,.2f}".rstrip("0").rstrip(".")
    return str(v)


def format_report(result, expected, observed):
    lines = []
    tag = lambda s: " (SYNTHETIC)" if s.get("synthetic") else ""                 # noqa: E731
    lines.append(f"expected: {expected['source']}{tag(expected)}  [{expected['kind']}, {expected.get('vehicle')}]")
    lines.append(f"observed: {observed['source']}{tag(observed)}  [{observed['kind']}, {observed.get('vehicle')}]")
    lines.append(f"pull threshold: current below -{result['amps']:g} A")
    lines.append("")
    w = max(len(r["metric"]) for r in result["rows"]) if result["rows"] else 20
    lines.append(f"{'metric':<{w}}  {'expected':>12}  {'observed':>12}  {'Δ (obs−exp)':>12}")
    lines.append("-" * (w + 44))
    for r in result["rows"]:
        lines.append(f"{r['metric']:<{w}}  {_fmt(r['expected']):>12}  {_fmt(r['observed']):>12}  {_fmt(r['delta']):>12}")
    per = [p for p in result["periods"] if p["expected_s"] or p["observed_s"] or p["expected_n"] or p["observed_n"]]
    if per:
        lines.append("")
        lines.append(f"{'id':<5} {'survey s':>9} {'expected s':>11} {'observed s':>11} {'exp lines':>10} {'obs lines':>10}")
        lines.append("-" * 61)
        for p in per:
            lines.append(f"{p['id']:<5} {_fmt(p['survey_s']):>9} {_fmt(p['expected_s']):>11} "
                         f"{_fmt(p['observed_s']):>11} {_fmt(p['expected_n']):>10} {_fmt(p['observed_n']):>10}")
        lines.append("periods come from a .jsonl stream's timestamps; a fixture only has line counts "
                     "per timeline frame (thinned)")
    if expected.get("synthetic") or observed.get("synthetic"):
        lines.append("")
        lines.append("A SYNTHETIC side is the simulator's: its Car-CAN lines are the encoder's and every "
                     "EV-CAN byte is ASSERTED. A match is consistency, not verification.")
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Compare an expected pull with an observed one.")
    ap.add_argument("expected", help="fixture .json, readings .db, or rx/# stream .jsonl")
    ap.add_argument("observed", help="the same kinds")
    ap.add_argument("--amps", type=float, default=DEFAULT_AMPS,
                    help=f"a pull starts when current goes below -AMPS (default {DEFAULT_AMPS:g})")
    ap.add_argument("--vehicle", default=None, help="profile for decoding (default: the input's)")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    args = ap.parse_args(argv)
    try:
        exp = load_series(args.expected, args.vehicle)
        obs = load_series(args.observed, args.vehicle)
    except (OSError, ValueError, json.JSONDecodeError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    result = compare(exp, obs, amps=args.amps)
    if args.json:
        print(json.dumps({"expected_source": exp["source"], "observed_source": obs["source"],
                          "expected_synthetic": exp.get("synthetic"), "observed_synthetic": obs.get("synthetic"),
                          **result}, indent=1, default=str))
    else:
        print(format_report(result, exp, obs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
